# General settings
domain: "https://vaultwarden.digitalprivacy.homes"
## Controls if new users can register
signups: "true"
## Invitations org admins to invite users, even when signups are disabled
invitations: "true"

# SMTP Email settings
use_smtp: false
email_host: ""
email_port: "587"
email_user: ""
email_pass: ""
email_from: ""
email_tls: "starttls"
email_timeout: "15"
email_from_name: vaultwarden.digitalprivacy.homes