---
- name: Install cockpit
  package:
    update_cache: true
    name: cockpit
    state: present

- name: Remove cockpit.issue. Web console link will be listed in /etc/issue.net.
  ansible.builtin.file:
    path: /etc/issue.d/cockpit.issue
    state: absent

- name: Copy nginx host file to proxy cockpit.
  copy:
    src: "files/cockpit.digitalprivacy.homes"
    dest: "/etc/nginx/sites-available/cockpit.digitalprivacy.homes"
    owner: "root"
    group: "root"
    mode: '0640'

- name: Create a symbolic link of cockpit.digitalprivacy.homes
  ansible.builtin.file:
    src: /etc/nginx/sites-available/cockpit.digitalprivacy.homes
    dest: /etc/nginx/sites-enabled/cockpit.digitalprivacy.homes
    owner: root
    group: root
    state: link
  notify:
    - Reload nginx

