namespace: digitalprivacy_homes
name: server
version: 0.6.1
readme: README.md
authors:
  - DIGITAL PRIVACY .HOMES <hello@chat.digitalprivacy.homes>
description: 'This collection provides solutions for digital privacy that are only intended for home use.'
license:
  - GPL-3.0-or-later
license_file: ''
tags:
  - server
  - digitalprivacy
  - privacy
  - linux
  - debian
  - adguardhome
  - cockpit
  - docker
  - firewalld
  - msmtp
  - nginx
  - portainer
  - searxng
  - unattended_upgrades
  - unbound
  - vaultwarden
  - desec
  - dyndns
  - wg_easy
  - tor
dependencies:
  ansible.posix: '>=1.0.0'
  community.crypto: '>=1.0.0'
repository: 'https://codeberg.org/digitalprivacy-homes/ansible-server/'
homepage: 'https://digitalprivacy.homes/'
documentation: 'https://digitalprivacy.homes/#faq'
issues: 'https://codeberg.org/digitalprivacy-homes/ansible-server/issues'
build_ignore:
  - .github
  - build
  - install_ansible_on_workstation.sh
