---
- name: Create directory wireguard.
  ansible.builtin.file:
    path: /opt/wireguard
    state: directory
    owner: "root"
    group: "root"
    mode: '0640'

- name: Copy docker-compose.yml to /opt/wireguard/
  ansible.builtin.copy:
    src: "files/docker-compose.yml"
    dest: "/opt/wireguard/docker-compose.yml"
    owner: "root"
    group: "root"
    mode: '0640'

- name: Pull and start image
  ansible.builtin.shell: cd /opt/wireguard/ && docker compose up -d

- name: Copy nginx host file to proxy wireguard.
  ansible.builtin.copy:
    src: "files/wireguard.digitalprivacy.homes"
    dest: "/etc/nginx/sites-available/wireguard.digitalprivacy.homes"
    owner: "root"
    group: "root"
    mode: '0640'

- name: Create a symbolic link of wireguard.digitalprivacy.homes
  ansible.builtin.file:
    src: /etc/nginx/sites-available/wireguard.digitalprivacy.homes
    dest: /etc/nginx/sites-enabled/wireguard.digitalprivacy.homes
    owner: root
    group: root
    state: link
  notify:
    - Reload nginx

- name: Open 51820/udp port for wireguard
  ansible.posix.firewalld:
    zone: public
    port: 51820/udp
    state: enabled
    permanent: yes
    immediate: yes
  notify:
    - Restart firewalld

- name: Get home public IP
  community.general.ipify_facts:
  register: public_ip

- name: Your public IP address, which you can use for wireguard (host) if you have a static IP address from your ISP. Or check if you have a desec dyndns domain below (in the next tasks) and use that as your host.
  ansible.builtin.debug:
    var: public_ip.ansible_facts.ipify_public_ip

- name: Checks if you have a desec domain in ddclient.
  ansible.builtin.shell: cat /etc/ddclient.conf | grep login | sed 's/login=//g'
  register: ddclient

- name: Shows the output of a ddclient domain "{{ ddclient.stdout }}".
  ansible.builtin.debug:
    var: ddclient.stdout

- name: Checks also for a desec domain vars.
  ansible.builtin.debug:
    msg: "{{ item.domain }}"
  with_items: "{{ desec }}"
  when: desec is defined

- name: These IPs (IPv4 & IPv6) are your server IPs. You can change the DNS server to your server in the admin panel of your wireguard installation (https://wireguard.digitalprivacy.homes/admin/config).
  ansible.builtin.debug:
    msg: "{{ item }}"
  with_items:
     - "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
     - "{{ ansible_default_ipv6.address | default(ansible_all_ipv6_addresses[0]) }}"
