---
- name: Install unbound
  ansible.builtin.package:
    update_cache: true
    name: 
    - unbound
    - resolvconf
    state: present

- name: Disable resolvconf+unbound hook. Otherwise unbound-resolvconf.service failed after reboot.
  ansible.builtin.shell: chmod -x /etc/resolvconf/update.d/unbound

- name: Copy config file
  ansible.builtin.copy:
    src: "files/unbound.conf"
    dest: "/etc/unbound/unbound.conf"
    owner: "root"
    group: "root"
    mode: '0644'
  notify:
    - Restart unbound
