---
- name: Install needed packages to enable unattended-upgrades.
  package:
    update_cache: yes
    name: 
      - "unattended-upgrades"
      - "apt-listchanges"
      - "needrestart"
    state: present

- name: Copy `52unattended-upgrades-local.j2` to `/etc/apt/apt.conf.d/`.
  template:
    src: "templates/52unattended-upgrades-local.j2"
    dest: "/etc/apt/apt.conf.d/52unattended-upgrades-local"
    owner: "root"
    group: "root"
    mode: '0644'
  with_items:
    - "{{ unattended_upgrades | default() }}"

- name: Copy `20auto-upgrades.j2` to `/etc/apt/apt.conf.d/`.
  template:
    src: "templates/20auto-upgrades.j2"
    dest: "/etc/apt/apt.conf.d/20auto-upgrades"
    owner: "root"
    group: "root"
    mode: '0644'
  with_items:
    - "{{ unattended_upgrades | default() }}"

- name: Copy `listchanges.conf.j2` to `/etc/apt/apt.conf.d/`.
  template:
    src: "templates/listchanges.conf.j2"
    dest: "/etc/apt/listchanges.conf"
    owner: "root"
    group: "root"
    mode: '0644'
  with_items:
    - "{{ unattended_upgrades | default() }}"
