---
- name: Install cargo package.
  ansible.builtin.package:
    update_cache: yes
    name: cargo
    state: present

- name: Install oniux.
  ansible.builtin.shell: cargo install --git https://gitlab.torproject.org/tpo/core/oniux --tag v0.5.0 oniux
  # If the build fails ignore it and keep going.
  ignore_errors: true
