---
- name: Clone searxng git repo
  ansible.builtin.git:
    repo: https://github.com/searxng/searxng-docker.git
    dest: /opt/searxng
    accept_hostkey: yes
    force: yes

- name: Copy .env file
  ansible.builtin.copy:
    src: "files/env"
    dest: "/opt/searxng/.env"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Copy settings.yml file
  ansible.builtin.copy:
    src: "files/settings.yml"
    dest: "/opt/searxng/searxng/settings.yml"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Set secret key
  shell: sed -i "s|ultrasecretkey|$(openssl rand -hex 32)|g" /opt/searxng/searxng/settings.yml

# Why this step? Check https://github.com/searxng/searxng-docker?tab=readme-ov-file#how-to-use-it
- name: Copy docker-compose.yaml.without_cap_drop file for the first start
  ansible.builtin.copy:
    src: "files/docker-compose.yaml.without_cap_drop"
    dest: "/opt/searxng/docker-compose.yaml"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Pull images and start
  ansible.builtin.shell: cd /opt/searxng/ && docker compose up -d

- name: Stop container again after the start
  ansible.builtin.shell: cd /opt/searxng/ && docker compose down

- name: Copy docker-compose.yaml after first start (cap_drop)
  ansible.builtin.template:
    src: "templates/docker-compose.yaml.j2"
    dest: "/opt/searxng/docker-compose.yaml"
    owner: "root"
    group: "root"
    mode: '0644'
  with_items:
    - "{{ searxng | default() }}"

- name: Final start
  ansible.builtin.shell: cd /opt/searxng/ && docker compose up -d

- name: Copy nginx host file to proxy searxng.
  ansible.builtin.copy:
    src: "files/searxng.digitalprivacy.homes"
    dest: "/etc/nginx/sites-available/searxng.digitalprivacy.homes"
    owner: "root"
    group: "root"
    mode: '0640'

- name: Create a symbolic link of searxng.digitalprivacy.homes
  ansible.builtin.file:
    src: /etc/nginx/sites-available/searxng.digitalprivacy.homes
    dest: /etc/nginx/sites-enabled/searxng.digitalprivacy.homes
    owner: root
    group: root
    state: link
  notify:
    - Reload nginx
    