---
- name: Add Docker APT repository
  ansible.builtin.deb822_repository:
    name: docker
    types: ["deb"]
    uris: "https://download.docker.com/linux/{{ ansible_distribution|lower }}"
    suites: "{{ ansible_distribution_release }}"
    components: [stable]
    signed_by: "https://download.docker.com/linux/debian/gpg"
    enabled: true

- name: Install docker
  ansible.builtin.package:
    update_cache: true
    name: 
      - "docker-ce" 
      - "docker-ce-cli" 
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: present

- name: Add local dns to docker default
  ansible.builtin.lineinfile:
    path: /etc/default/docker
    insertafter: '^#DOCKER_OPTS='
    line: 'DOCKER_OPTS="--dns 127.0.0.1"'
  notify:
    - Restart Docker

- name: Add docker.service override.conf file to make docker.service start after AdGuardHome.service and unbound.service.
  ansible.builtin.copy:
    src: files/override.conf
    dest: "/etc/systemd/system/docker.service.d/"
    owner: "root"
    group: "root"
    mode: "0644"
  notify:
    - Restart Docker
