---
- name: Copy whiptail script digitalprivacy.sh to /usr/local/bin/
  ansible.builtin.copy:
    src: files/digitalprivacy.sh
    dest: "/usr/local/bin/digitalprivacy"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Copy script digitalprivacy-update_ip.sh to /usr/local/bin/
  ansible.builtin.template:
    src: templates/digitalprivacy-update_ip.sh.j2
    dest: "/usr/local/bin/digitalprivacy-update_ip"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Run digitalprivacy-update_ip.sh every reboot.
  ansible.builtin.cron:
    name: "Run digitalprivacy-update_ip.sh every reboot."
    special_time: reboot
    job: "sleep 10s && /usr/local/bin/digitalprivacy-update_ip > /dev/null 2>&1"

- name: Copy script digitalprivacy-update_certificates.sh to /usr/local/bin/
  ansible.builtin.copy:
    src: files/digitalprivacy-update_certificates.sh
    dest: "/usr/local/bin/digitalprivacy-update_certificates"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Run digitalprivacy-update_certificates.sh every week.
  ansible.builtin.cron:
    name: "Run digitalprivacy-update_certificates.sh every week."
    special_time: weekly
    job: "/usr/local/bin/digitalprivacy-update_certificates > /dev/null 2>&1"

- name: Copy /etc/issue
  ansible.builtin.template:
    src: templates/issue.j2
    dest: "/etc/issue"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "{{ digitalprivacy | default() }}"

- name: Copy issue.net to /etc/issue.net
  ansible.builtin.template:
    src: templates/issue.net.j2
    dest: "/etc/issue.net"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "{{ digitalprivacy | default() }}"

- name: Copy issue.net to /etc/motd
  ansible.builtin.template:
    src: templates/issue.net.j2
    dest: "/etc/motd"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - "{{ digitalprivacy | default() }}"

- name: Add autostart for digitalprivacy whiptail script to ~/.bashrc 
  ansible.builtin.shell: echo "/usr/local/bin/digitalprivacy" >> ~/.bashrc
  become_user: "{{ ansible_user }}"
