---
galaxy_info:
  author: Dan (digitalprivacy.diy / digitalprivacy.homes)
  description: This Ansible role provides docker / docker compose. A set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers.
  company: "https://docker.com"
  license: Apache License 2.0
  min_ansible_version: 2.15.0
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - docker
    - containers
    - images
    - management
dependencies: []
